### PR TITLE
Fix last point orientation

### LINKED ISSUE #8: Last orientation of grinding line is wrong
For the last pose of a grinding line there is no "next point" to compute the orientation so it is copied from the last pose.

This doesn't work:
last_normal

### PR DESCRIPTION
**Pull request by KevinBollore**
Fix #8 
@VictorLamoine, @Nandite, ready for review.

### CODE REVIEW

File: bezier_library/src/bezier_grinding_surfacing.cpp [hunk 1]
```diff
@@ -442,25 +442,11 @@ bool BezierGrindingSurfacing::generateRobotPosesAlongStripper(const vtkSmartPoin
   // are stored into the container point_normal_map.
   // We now iterate through this map and generate robot pose for each point
   Eigen::Affine3d last_pose(Eigen::Affine3d::Identity());
+  // Create a point which is the point before the last point
+  Eigen::Vector3d before_last_point(point_normal_table[point_normal_table.size()-2].first);
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_grinding_surfacing.cpp]: I'm not saying this doesn't work but this is really ugly.

Why is the old way of copying the pose not working?

Comment (KevinBollore) [inline bezier_library/src/bezier_grinding_surfacing.cpp]: I know that is ugly, but I did'nt find on the moment an other way to write it...
In fact, copying `last_pose.linear()` gave the orientation to follow a point, that's why `pose.linear()` had a bad orientation, because it followed the same point.

**Comment by KevinBollore** [comment]
@VictorLamoine It's OK with Travis.
