### PR TITLE
Remove unexpected holes in upper par of mesh

### LINKED ISSUE #10: keepUpperPartofDilatedMesh creates holes in the mesh
The dilated mesh sometimes contains holes because of a too big extrication radius (see https://github.com/ros-industrial-consortium/bezier/issues/3).

The filtering of the upper part also creates holes, this can be easily seen by comparing `dilated_mesh.stl`
and `extrication_mesh.stl` in `bezier_library/meshes/`

Before
---
before

After
---
after

### PR DESCRIPTION
**Pull request by KevinBollore**
Fix #10 
@VictorLamoine, @Nandite ready for review.

### CODE REVIEW

File: bezier_library/src/bezier_library.cpp [hunk 1]
```diff
@@ -524,28 +524,46 @@ bool Bezier::keepUpperPartofDilatedMesh(vtkSmartPointer<vtkPolyData> &base_polyd
...
-
-    // Get closest point normal
-    double normal[3];
-    point_normal_array->GetTuple(id, normal);
-    Eigen::Vector3d normal_vector(normal);
-    direction_vector.normalize();
-    normal_vector.normalize();
+    // Looking for the 2 closest points of cellCenter
+    unsigned number_of_points = 2;
+    vtkSmartPointer<vtkIdList> IDclosestPoints = vtkSmartPointer<vtkIdList>::New();
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_library.cpp]: Naming conventions

File: bezier_library/src/bezier_library.cpp [hunk 2]
```diff
@@ -524,28 +524,46 @@ bool Bezier::keepUpperPartofDilatedMesh(vtkSmartPointer<vtkPolyData> &base_polyd
...
+    kd_tree->FindClosestNPoints(number_of_points, cell_center, IDclosestPoints);
+
+    std::vector<double[3]> closest_points_vector(number_of_points);
+    std::vector<Eigen::Vector3d, Eigen::aligned_allocator<Eigen::Vector3d> > directions_vector(number_of_points);
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_library.cpp]: http://docs.ros.org/jade/api/eigen_stl_containers/html/eigen__stl__vector__container_8h_source.html

EigenSTL::vector_Vector3d

File: bezier_library/src/bezier_library.cpp [hunk 3]
```diff
@@ -524,28 +524,46 @@ bool Bezier::keepUpperPartofDilatedMesh(vtkSmartPointer<vtkPolyData> &base_polyd
...
+      normals_normalized_vector[i].normalize();
+    }
 
     // Keep the cell only if it belongs to the upper part of the mesh
     if (!vtkMath::IsFinite(cell_center[0]) ||
         !vtkMath::IsFinite(cell_center[1]) ||
-        !vtkMath::IsFinite(cell_center[2])
-        || normal_vector.dot(direction_vector) <= 0)
+        !vtkMath::IsFinite(cell_center[2]) ||
+        (normals_normalized_vector[0].dot(directions_vector[0]) <= 0 && normals_normalized_vector[1].dot(directions_vector[1]) <= 0))
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_library.cpp]: Break this line in two, it's too long.

**Comment by VictorLamoine** [comment]
Travis doesn't compile:
https://travis-ci.org/InstitutMaupertuis/bezier/jobs/142228297#L3590

File: bezier_library/src/bezier_library.cpp [hunk 4]
```diff
@@ -524,28 +524,47 @@ bool Bezier::keepUpperPartofDilatedMesh(vtkSmartPointer<vtkPolyData> &base_polyd
...
+    vtkSmartPointer<vtkIdList> id_closest_points = vtkSmartPointer<vtkIdList>::New();
+    kd_tree->FindClosestNPoints(number_of_points, cell_center, id_closest_points);
+
+    std::vector<double[3]> closest_points_vector(number_of_points);
+    EigenSTL::vector_Vector3d directions_vector(number_of_points);
+    std::vector<double[3]> normals_vector(number_of_points);
+    EigenSTL::vector_Vector3d normals_normalized_vector(number_of_points);
+
+    // Store variable into vectors
+    for(vtkIdType i = 0; i < number_of_points ; ++i)
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_library.cpp]: Extra space before `;`

**Comment by VictorLamoine** [comment]
Ok to merge as soon as Travis is fixed

File: bezier_library/src/bezier_library.cpp [hunk 5]
```diff
@@ -530,28 +530,52 @@ bool Bezier::keepUpperPartofDilatedMesh(vtkSmartPointer<vtkPolyData> &base_polyd
...
+      // Compute vector between cell_center on dilated_polydata and closest_point i on base_polydata
+      direction_vector[0] = cell_center[0] - closest_point_vector[0];
+      direction_vector[1] = cell_center[1] - closest_point_vector[1];
+      direction_vector[2] = cell_center[2] - closest_point_vector[2];
+
+      // Get normal of closest_point i
+      point_normal_array->GetTuple(id_closest_points->GetId(i), normal);
+      direction_vector.normalize();
+      
+      Eigen::Vector3d normal_3d(normal[0], normal[1], normal[2]);
```
Comment (VictorLamoine) [inline bezier_library/src/bezier_library.cpp]: Eigen::Vector3d normal_3d(normal);
